@startuml
'https://plantuml.com/sequence-diagram
participant TextUI as ui
participant Game as game

participant Tax as Tax
participant Field  as field


game -> game : landAndAct(f)
game -> Tax : msg = onLand(player)
Tax -> field : msg = super.onLand(player);
field --> Tax : "Du er landet på skat."
Tax -> Tax : msg+="Du skal betale et beløb der svarer til 10 % af dine aktiver.\nVil du hellere betale et fast beløb på 4000kr?(Y/N)"
Tax --> game:   "Du er landet på skat. Du skal betale et beløb der svarer til 10 % af dine aktiver.\n Vil du hellere betale et fast beløb på 4000kr?(Y/N)"

game -> ui : response = promptBinary( msg )

ui --> game : true
'game -> field : msg = processResponse(player, response)

alt response == true
     game -> Tax: onAccept()
      Tax -> Player: worth=getTotalWorth()
     Tax -> Bank: withdraw(worth*0.1, player))
     Tax --> game: "Egon har betalt 10% i skat"
   else
     game -> Tax: onReject()
      Tax -> Bank: withdraw(4000,player))
     Tax --> game: "Egon har betalt 4000kr i skat"
end



game -> ui : displayMessage( msg )


@enduml
